# Generated by Django 6.0 on 2025-12-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='grade',
            new_name='city',
        ),
    ]
